MODEL:
  NAME: bank_tab
  HIDDEN_SIZE: 32
  NUM_LAYERS: 3
  NUM_HEADS: 4

TRAIN:
  RUN_NAME: hidden(32)-layers(3)-heads(4)
  BATCH_SIZE: 128
  EPOCHS: 10
  PATIENCE: 3
  
  FIRST_CYCLE_STEPS: 50
  CYCLE_MULT: 1.0
  MAX_LR: 0.001
  MIN_LR: 0.00001
  WARMUP_STEPS: 10
  GAMMA: 0.5
